# .github/workflows/build-on-pr.yml
name: Build on Pull Request

on:
  pull_request:
    branches:
      - main 

jobs:
  # Basic build job that runs for ALL pull requests (including forks)
  basic_build:
    runs-on: ubuntu-latest
    # Always run this job - no conditions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  

      - name: Install dependencies
        run: yarn install

      - name: Public build (no secrets)
        run: echo "Basic build verification passed"

  # Enhanced build job that includes secrets (only for trusted contributors)
  full_build:
    runs-on: ubuntu-latest
    # Only run this job if the PR is from the same repo (not a fork)
    # Or if the actor has write access to the repository
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.pull_request.author_association == 'COLLABORATOR' || github.event.pull_request.author_association == 'MEMBER' || github.event.pull_request.author_association == 'OWNER'
    needs: basic_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  

      - name: Install dependencies
        run: yarn install

      - name: Full build with secrets
        env:
          HACKATIME_API_TOKEN: "doesntmatter"
          LOOPS_TRANSACTIONAL_SIGNIN_EMAIL_ID: "notimportant"
          LOOPS_TRANSACTIONAL_NOTIFICATION_EMAIL_ID: "notimportant"
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          GRAPHITE_HOST: ${{ secrets.GRAPHITE_HOST }}
          NODE_ENV: "development"
        run: yarn build
